#3 standardize mailchimp endpoint
slingr-stack/mailchimp-endpoint pull request #4
Opened 2023-04-25 16:10 UTC by agreggio-slingr

Pull request for the topic https://github.com/slingr-stack/mailchimp-endpoint/issues/3 created by @agreggio-slingr

## What does it do?
This ticket implements the use of slingr-helpgen, whereby it modifies existing functions, adds basic functions and step flows.

## How to test it?
Make calls from the platform for example using the console using the information provided in the documentation.

## Implementation notes
Create new version of the endpoint, it is not compatible with previous versions.

## Implementation notes
Create a new tags changing the major version and deploy to the platform.

2023-04-25 17:52 UTC, sebasmoyano commented
#approve

2023-04-25 19:05 UTC, pasaperez-slingr requested changes
Review Readme for changes in helpers, copy documentation generated from flows step, review consistency.

2023-04-25 19:05 UTC, pasaperez-work commented on endpoint.json
>      "mailchimp-fn-helpers.js",
Remove unnecessary calls, or the builder will fail.

2023-04-25 19:05 UTC, pasaperez-slingr commented on endpoint.json
The functions:
_convertDateToTimestamp_convertDateToTimestamp ... _getResourceById
they are deprecated according to the new functions.js ... remove from the descriptor and the support in the main file: "src/main/java/io/slingr/endpoints/mailchimp/" .
Standardize the main file to leave http calls (through the framework) or as little custom code as possible for migration.

2023-04-25 19:10 UTC, pasaperez-slingr commented on flowSteps/apiCallMailchimp/step.json
> +            "label": "File Downloaded",
Could this field be a switcher (boolean)?

2023-04-26 15:53 UTC, pasaperez-slingr approved these changes

2023-04-26 15:53 UTC, pasaperez-slingr commented
#approve

2023-04-26 15:53 UTC, merged